#Every variable is specified in the .env file
services:
  pihole:
    image: pihole/pihole:2026.05.0
    container_name: pihole
    environment:
      FTLCONF_misc_tz: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_PASS}
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    depends_on:
      - dnsproxy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add: #Giving capabilities only needed to run not more 
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
      SERVERURL: ${ROUTER_IP}
      SERVERPORT: 51820
      PEERS: ${DEVICES}
      PEERDNS: ${PIHOLE_IP}
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - SUBDOMAINS=${SDOMAIN}
      - TOKEN=${TOKEN}
    restart: unless-stopped

  dnsproxy:
    container_name: dnsproxy
    image: adguard/dnsproxy:latest
    command: -l 0.0.0.0 -p 5053 -u https://dns.quad9.net/dns-query -b 9.9.9.9
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:2'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - TZ=Europe/Athens
    volumes: #in any case for the ssl certificate to not be lost
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false #this was added after the first vaultwarden account was created
      - EXTENDED_LOGGING=true
    volumes:
      - ./vaultwarden:/data/

  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./uptime-kuma-data:/app/data


  dashy:
    image: lissy93/dashy:4.x
    container_name: dashy
    volumes:
      - ./dashy/user-data:/app/user-data
      - ./custom-theme.css:/app/public/custom-theme.css:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped


  dozzle:
    image: amir20/dozzle:v10
    container_name: dozzle
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
      - DOCKER_HOST=tcp://socket-proxy:2375
    depends_on:
      - socket-proxy
    volumes:
      - ./dozzle/data:/data
    restart: unless-stopped

  socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: socket-proxy
    environment:
    #setting up dozzle capabilitities
      - CONTAINERS=1
      - INFO=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
