#Every variable is specified in the .env file
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      FTLCONF_misc_tz: ${TIMEZONE}
      FTLCONF_webserver_api_password: ${PIHOLE_PASS}
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
     #maybe useless anymore - "8080:80/tcp"
    depends_on:
      - dnsproxy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add: #Giving capabilities only needed to run not more 
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
      SERVERURL: ${ROUTER_IP}
      SERVERPORT: 51820
      PEERS: ${DEVICES}
      PEERDNS: ${PIHOLE_IP}
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
      - SUBDOMAINS=${SDOMAIN}
      - TOKEN=${TOKEN}
    restart: unless-stopped

  dnsproxy:
    container_name: dnsproxy
    image: adguard/dnsproxy:latest
    command: -u https://dns.quad9.net/dns-query -b 0.0.0.0 -p 5053 --bootstrap 9.9.9.9
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
#      - '81:81'
      - '443:443'
    environment:
      - TZ=Europe/Athens
    volumes: #in any case for the ssl certificate to not be lost
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false #this was added after the first vaultwarden account was created
    volumes:
      - ./vaultwarden:/data/

