name: Bash Script CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
#node 20 actions are deprecated so using node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  arch_shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
