name: Bash Script CI
on:
  push:
    branches: ["main"]
    paths: #making it run only if .sh files are changed or this file is changed
      - 'scripts/*.sh'
      - '.github/workflows/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'scripts/*.sh'

jobs:
  arch_shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
